version: 2.1

jobs:
  build:
    docker:
      - image: eddieorg/cfn-lint:latest_test
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
   
    working_directory: /Users/eddiezhang/DevOps/eddiez0719/tmp/
    steps:
      - checkout
      - setup_remote_docker:
           version: 19.03.13
      - run:
           name: Install Docker client
           command: apk add docker-cli
      - run:
           name: Install curl and jq
           command: |
                 apk update && apk add curl curl-dev bash
                 apk add --upgrade jq
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run: ./find_latest.sh
      - run echo "my artifact file" > /Users/eddiezhang/DevOps/eddiez0719/tmp/test;
      - store_artifacts:
          path: /Users/eddiezhang/DevOps/eddiez0719/tmp/test
          destination: artifact-file
          when: always

# Orchestrate our job run sequence
workflows:
  DeployCI:
    jobs:
      - build
