version: 2.1

jobs:
  build:
    docker:
      - image: eddieorg/cfn-lint:latest_test
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
           version: 19.03.13
      - run:
           name: Install Docker client
           command: apk add docker-cli
      - run:
           name: Install curl and jq
           command: |
                 apk update && apk add curl curl-dev bash
                 apk add --upgrade jq
      - run: ./find_latest.sh

# Orchestrate our job run sequence
workflows:
  DeployCI:
    jobs:
      - build
