version: 2.1
orbs:
  jq: circleci/jq@2.2.0
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: eddieorg/cfn-lint:latest_test
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run:
           name: Install curl and jq
           command: |
                 apk update && apk add curl curl-dev bash
                 apk add --upgrade jq
      - run: ./find_latest.sh

# Orchestrate our job run sequence
workflows:
  DeployCI:
    jobs:
      - build
